:website:
  :id: "http://alexn.org"
  :title: "alexn.org"
  :description: Blog about programming and personal projects, by Alexandru Nedelcu
  :hostname: "alexn.org"
  :domain: "alexn.org"
  :root_url: "https://alexn.org"
