:website:
  :id: "http://bionicspirit.com"
  :title: "Bionic Spirit"
  :description: by Alexandru Nedelcu
  :hostname: "bionicspirit.com"
  :domain: "bionicspirit.com"
  :root_url: "https://bionicspirit.com"
