:website:
  :id: "https://alexn.org"
  :title: "Alexandru Nedelcu"
  :description:
    Senior software developer, polyglot without loyalty,
    Scala enthusiast.
  :hostname: "alexn.org"
  :domain: "alexn.org"
  :root_url: "https://alexn.org"
